### ISSUE TITLE
Enhance survey template creation - order of sections

### ISSUE THREAD

**Issue by drwlodarski** [gamification-survey-platform/client#52]
Currently, the re-ordering of sections drag and drop mechanism doesn't work correctly - it's pretty random so probably difficult to debug.
As a workaround, can we please:
1) fix the default "artefact" section to always be on top,
2) adapt the behaviour so that when a new section is added, it goes below the existing ones rather than on top.

<img width="1514" alt="image" src="https://github.com/gamification-survey-platform/client/assets/111450974/45d5484e-2556-4bda-8773-ac8afe33f277">

**Comment by xinyuew3S2024** [comment]
I will take a look today.
