### ISSUE TITLE
gen AI icon misses indication of gamification points

### ISSUE THREAD

**Issue by drwlodarski** [gamification-survey-platform/client#57]
Gamified users that click on gen AI assistant should receive points for doing so (5 pts) - the target amount of points should be indicated somewhere next to the assistant icon. This could be a colorful circle with the number in it.
The objective is to incite the users to solicit feedback - this is an important bug.

**Comment by audrey-zhou** [comment]
I implemented this logic when user is using gpt assistant for the first time for this assignment, there would be bonus icon in the feedback pop up page. Did you use a new student when checking this functionality?

**Comment by drwlodarski** [comment]
I saw it for one of the accounts, however we want to let students know before soliciting feedback, that this action will be rewarded. Hence, the incentive should be displayed somewhere near the assistant icon (not inside of the feedback pop up page - although this can remain).

**Comment by xinyuew3S2024** [comment]
@drwlodarski @audrey-zhou do we have this implemented or is this still pending to be done? If this needed, i can take on this task. Just to confirm my understanding: we want to include an icon with a 5 in a circle to indicate to gamified users that there is a 5-point bonus available if they use the AI assistant. It just displays as a message to inform students like kind of reward?

**Comment by audrey-zhou** [comment]
![5](https://github.com/gamification-survey-platform/client/assets/136390132/23f745ed-9eb2-4855-ab63-89c33bfb08a8)
This is still pending, so you can take it! I found this icon that maybe you can use.

**Comment by drwlodarski** [comment]
Hi @xinyuew3S2024 you almost got it right - the idea is to place is next (on top?) of the gen AI icon - we want students to see it during the survey filling in process. Whenever we hover over the genAI/points it should be explained that these are granted e.g. "Asking feedback assistant for insight for the first time grants 5 points in every assignment". Once they were granted, the AI label should not include that part.
