### ISSUE TITLE
Unable to submit a review although all mandatory answers were provided

### ISSUE THREAD

**Issue by drwlodarski** [gamification-survey-platform/client#58]
For the user hanxiz I am unable to submit a review despite filling in all answers. This doesn't reproduce for another account I tried (e.g. wenxiyan). I suspect it has to do with the artifact that doesn't load properly (there is no preview)?

<img width="1420" alt="Screenshot 2024-04-14 at 11 20 32" src="https://github.com/gamification-survey-platform/client/assets/111450974/85a0021d-cbc4-4a46-b766-c1a6080eb328">

**Comment by drwlodarski** [comment]
What is more, it seems the gamification points were granted many times for the action of submitting the feedback. The user now has 315 points altough did not provide any reviews.

**Comment by rhuang4F2023** [comment]
Hi Rafal, this account should be non-gamified mode, make sure to clear the browser cache before switch account. Not sure if its the reason to make some unexpected bug. There is the preview, very small '1' from account 'yukew'. I tried to login and finish a optional review for 'chaosg', its working well, and this record has been shown on submission report.
<img width="1036" alt="Screenshot 2024-04-14 at 1 32 04 PM" src="https://github.com/gamification-survey-platform/client/assets/143446333/97fa78ba-43bc-4686-9a78-fcaf9ff7ce90">

**Comment by drwlodarski** [comment]
Hi Terry,

I was able to reproduce the problem for another user - I think it has to do with the artifact uploaded (as it appears the same way - "1").
Could you please investigate what is the issue and if it can be fixed?

User: wenxiyan (non-gamified)
Review for: zekain

All best,
Rafal

**Comment by drwlodarski** [comment]
This issue persist for gamified users as well: e.g any review to perform by pkotchav

**Comment by rhuang4F2023** [comment]
Oh I know, there is an input box in the slide review, you should type something here. I assumed its intended to give a feedback for slide? And the small '1' actually is the slide pdf review (the pdf file only contains '1') which uploaded by users. Give it a try. I have used wenxiyan (non-gamified) this account to submit review for zekain.
<img width="1059" alt="Screenshot 2024-04-15 at 1 28 52 PM" src="https://github.com/gamification-survey-platform/client/assets/143446333/18debf66-0936-4c1a-843c-f7f2297b3b87">

**Comment by drwlodarski** [comment]
Hi Terry, that explains - thank you! 
As the artefact is an automatic section of a survey, **could we make it optional by default?** We do not require students to provide feedback on specific slides but the preview is very useful to refresh memory concerning a presentation.
