### ISSUE TITLE
Leaderboard displays incorrect results

### ISSUE THREAD

**Issue by drwlodarski** [gamification-survey-platform/client#61]
The leaderboard screen does not work correctly:
1) every user has the 1st spot (Ranking displayed as 1)
2) every user has the gold trophy associated

http://gamification-platform-client.s3-website-us-west-1.amazonaws.com/leaderboard

<img width="1419" alt="image" src="https://github.com/gamification-survey-platform/client/assets/111450974/b7779d38-a0a2-41af-b62e-90ee971c112e">

**Comment by hanqidS2023** [comment]
fixed as [https://github.com/gamification-survey-platform/client/commit/052c49991c4e98fa154455469f0b99cf4dd96c40](url)
