### ISSUE TITLE
Deactivate "mood analysis" when providing answers in a survey

### ISSUE THREAD

**Issue by drwlodarski** [gamification-survey-platform/client#65]
There is another obsolate functionality that seems to be re-activated when filling in a survey - for some sections, "mood analysis" is performed and a emoji displayed. Could we please have this removed/deactivated?

<img width="1309" alt="Screenshot 2024-04-15 at 08 47 21" src="https://github.com/gamification-survey-platform/client/assets/111450974/887084ba-1086-48c0-866a-3110064c86c1">

**Comment by drwlodarski** [comment]
Hi @audrey-zhou I was wondering if this issue was fixed? If so, could you please close it?

**Comment by audrey-zhou** [comment]
Done in [here](https://github.com/gamification-survey-platform/client/commit/f653491c5ba034e0970fa3f24971643aeda5eadc)
