### ISSUE TITLE
Rewards screen incorrectly displayed reward purchase date

### ISSUE THREAD

**Issue by drwlodarski** [gamification-survey-platform/client#70]
I detected a small issue with the rewards screen in the instructor view - In "Student Purchases" table, the "Date Purchased" column display's today's date instead of the actual date when a reward was purchased by a student.

<img width="1104" alt="image" src="https://github.com/gamification-survey-platform/client/assets/111450974/8a4f5ddc-16d8-4e92-9e06-2a9560cae9d1">

**Comment by rhuang4F2023** [comment]
It's fix now : )
