### ISSUE TITLE
Student report doesn't display most of the sections correctly (lack of content)

### ISSUE THREAD

**Issue by drwlodarski** [gamification-survey-platform/client#71]
For students that had their artefact reviewed by peers, they can access a summary report of these evaluations.
There seems to be a regression and currently, only open-ended answers are displayed in the report.
Any student can be used for testing purposes, e.g. yukew/Pass-2024! (below)

<img width="1181" alt="image" src="https://github.com/gamification-survey-platform/client/assets/111450974/7dd8190a-193c-40bd-9d29-a4bdbc7919b6">

**Comment by hanqidS2023** [comment]
<img width="508" alt="Screenshot 2024-05-03 at 11 08 10 PM" src="https://github.com/gamification-survey-platform/client/assets/123215156/065bcce8-62cf-46d3-8f8a-d644738f7ba2">
Fixed with https://github.com/gamification-survey-platform/server/commit/5387ac62e19f41e45b617cf68b84e559257ef22b
